### ISSUE TITLE
cx_freeze related TODO

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#6]
Currently, after freezeApp.py is used to build the stand alone application folder / exe, the following manual steps must be done. These steps should be automated.
- [x] Rename the app exe directory to something user friendly (like 'MarkWrite')
- [x] Rename the app exe to 'MarkWrite.exe'
- [x]  Copy the markwrite/resources folder into the top level app exe folder
- [x]  [Optional] Copy the test_data folder into the top level app exe folder

**Comment by isolver** [comment]
Done.
